name: nyc-taxi
schedule: daily
start_date: "2022-01-01"

default_connections:
  google_cloud_platform: gcp-default

variables:
  taxi_types:
    type: array
    items:
      type: string
    default: ["yellow", "green"]
